ДЗ Тестирование
Karenanna/JU pull request #1
Opened 2023-03-07 14:45 UTC by Karenanna

Проверьте пожалуйста ДЗ Тестирование

2023-03-08 09:28 UTC, alekseykoshelev requested changes

2023-03-08 09:28 UTC, alekseykoshelev commented on src/test/java/pro/sky/ju/UserTest.java
> +        Assertions.assertEquals(user.getLogin(), user.getEmail());
Тут ты проверяешь, что у пользователя, которого ты создал разные логин и емайл, но ничего не мешает мне создать пользователя с одинаковыми значениями. Чтобы запретить это делать, нужно добавить проверку в конструктор. Хорошим вариантом будет выкидывать эксепшен если были переданы такие аргументы. 
В тестах это можно будет проверить через assertThrows(), проверить именно то, что при передаче одинаковых аргументов выбрасывается эксепшен

2023-03-08 09:28 UTC, alekseykoshelev commented on src/test/java/pro/sky/ju/UserTest.java
> +        user = new User();
Лучше назвать поля по разному, сейчас у тебя значение перезаписывается, то есть все зависит от того в каком порядке вызываются методы. Лучше не зависеть от этого. 
Также нужно добавить еще тест, что при вызове пустого конструктора поля остаются null

2023-03-09 08:25 UTC, Karenanna commented
Сделал работу над ошибками ДЗ Тестирование

2023-03-10 06:15 UTC, alekseykoshelev commented on src/test/java/pro/sky/ju/UserTest.java
> +            new User("bobrov", "bobrov");
Тест ты добавил, но вот в конструкторе у тебя все еще нет проверки.

2023-03-11 07:38 UTC, Karenanna commented
Сделал работу над ошибками

2023-03-12 06:33 UTC, Karenanna commented
Добавил в конструктор условие.

2023-03-13 11:07 UTC, merged